"""Tests for projects 17-20: time series, target encoding, regularisation, market basket.

Three of these assert a *failure* rather than a capability - that a metric is fooled, that a
worthless column scores well, that a rule dissolves. Those are the claims the projects make,
so those are the ones that need to be pinned.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parent.parent
for project in (
    "17-time-series",
    "18-encoding-leakage",
    "19-regularisation",
    "20-market-basket",
):
    sys.path.insert(0, str(ROOT / "projects" / project))

from basket import (  # noqa: E402
    build_baskets,
    build_rules,
    holdout_check,
    item_counts,
    pair_counts,
    permutation_null,
)
from encoding import (  # noqa: E402
    NaiveTargetEncoder,
    OutOfFoldEncoder,
    TrainOnlyEncoder,
    cardinality_profile,
    category_means,
)
from regularise import bootstrap_selection, fit_penalised, jaccard, pairwise_stability  # noqa: E402
from timeseries import (  # noqa: E402
    Drift,
    Mean,
    RandomWalk,
    mase,
    rolling_backtest,
    spurious_regression,
    stationarity_verdict,
)

# --- 17 · time series ------------------------------------------------------


def test_spurious_regression_manufactures_significance_in_levels():
    """Granger & Newbold, measured. Two unrelated random walks, one regression.

    This is the claim the project rests on: in levels, the great majority of unrelated pairs
    come back significant. In differences, the rate falls to what a 5% test should give.
    """
    result = spurious_regression(400, trials=120, seed=1)
    levels = result[result["basis"] == "levels"]["significant"].mean()
    differences = result[result["basis"] == "differences"]["significant"].mean()

    assert levels > 0.7
    assert differences < 0.12
    assert result[result["basis"] == "levels"]["abs_t"].median() > 5.0


def test_adf_and_kpss_have_opposite_nulls():
    """The fact that makes them disagree, and that is stated almost nowhere."""
    rng = np.random.default_rng(2)
    walk = np.cumsum(rng.normal(size=600))
    noise = rng.normal(size=600)

    unit_root = stationarity_verdict(walk, "random walk")
    stationary = stationarity_verdict(noise, "white noise")

    assert not unit_root.adf_says_stationary  # ADF fails to reject its unit-root null
    assert not unit_root.kpss_says_stationary  # KPSS rejects its stationarity null
    assert unit_root.verdict == "non-stationary"

    assert stationary.adf_says_stationary
    assert stationary.kpss_says_stationary
    assert stationary.verdict == "stationary"


def test_random_walk_is_unbeatable_on_a_random_walk():
    """A drift or a trailing mean cannot beat the last value when there is no signal."""
    rng = np.random.default_rng(3)
    series = np.cumsum(rng.normal(size=1200))
    scores = (
        rolling_backtest(series, [RandomWalk(), Mean(24)], horizon=12, folds=20, minimum=300)
        .groupby("model")["mase"]
        .mean()
    )
    assert scores["Random walk (last value)"] < scores["Trailing mean (24)"]


def test_drift_beats_the_random_walk_when_there_actually_is_a_drift():
    rng = np.random.default_rng(4)
    series = np.cumsum(rng.normal(loc=0.3, scale=1.0, size=1200))
    scores = (
        rolling_backtest(series, [RandomWalk(), Drift()], horizon=12, folds=20, minimum=300)
        .groupby("model")["mase"]
        .mean()
    )
    assert scores["Drift"] < scores["Random walk (last value)"]


def test_mase_is_one_for_the_naive_forecast_and_nan_on_a_flat_history():
    history = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    # A perfect forecast has zero error whatever the scale.
    assert mase([6.0, 7.0], [6.0, 7.0], history) == 0.0
    # A flat history has no naive error to scale by, and nan is the honest answer.
    assert np.isnan(mase([1.0], [2.0], np.ones(10)))


# --- 18 · target encoding --------------------------------------------------


def _leaky_frame(n: int = 6000, cardinality: int = 1500, seed: int = 0) -> tuple:
    """A categorical with no relationship to the target at all."""
    rng = np.random.default_rng(seed)
    categories = rng.integers(0, cardinality, size=n).astype(str)
    y = rng.binomial(1, 0.3, size=n)
    return categories, y


def test_naive_encoding_of_a_worthless_column_correlates_with_the_target():
    """The leak, isolated. The column is random; the encoding is not.

    A category appearing once is encoded with its own target exactly, so the encoded feature
    correlates with the label it was built from - on a column generated by a random number
    generator.
    """
    categories, y = _leaky_frame()
    split = len(y) // 2
    encoded_train, _ = NaiveTargetEncoder().fit_transform(
        categories[:split], y[:split], categories[split:], y[split:]
    )
    correlation = float(np.corrcoef(encoded_train, y[:split])[0, 1])
    assert correlation > 0.5


def test_out_of_fold_encoding_of_the_same_column_correlates_with_nothing():
    """The correct version, on identical data. The contrast is the whole project."""
    categories, y = _leaky_frame()
    split = len(y) // 2
    encoded_train, _ = OutOfFoldEncoder(folds=5, smoothing=20.0).fit_transform(
        categories[:split], y[:split], categories[split:], y[split:]
    )
    correlation = float(np.corrcoef(encoded_train, y[:split])[0, 1])
    assert abs(correlation) < 0.1


def test_train_only_encoding_leaks_into_training_but_not_into_test():
    """The half-fix: the test score becomes honest and the model stays broken."""
    categories, y = _leaky_frame(seed=1)
    split = len(y) // 2
    train_encoded, test_encoded = TrainOnlyEncoder().fit_transform(
        categories[:split], y[:split], categories[split:], y[split:]
    )
    assert float(np.corrcoef(train_encoded, y[:split])[0, 1]) > 0.4
    assert abs(float(np.corrcoef(test_encoded, y[split:])[0, 1])) < 0.1


def test_smoothing_shrinks_rare_categories_toward_the_prior():
    categories = np.array(["rare", "common", "common", "common", "common", "common"])
    target = np.array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0])
    prior = float(target.mean())

    raw = category_means(categories, target, prior=prior, smoothing=0.0)
    smoothed = category_means(categories, target, prior=prior, smoothing=5.0)

    assert raw["rare"] == 1.0  # the row's own target, unchanged
    assert abs(smoothed["rare"] - prior) < abs(raw["rare"] - prior)


def test_cardinality_profile_counts_every_row_once():
    categories = np.array(["a"] * 100 + ["b"] * 3 + ["c"])
    profile = cardinality_profile(categories)
    assert profile["rows"].sum() == len(categories)
    assert profile["categories"].sum() == 3
    assert profile.loc[profile["appearances"] == "1", "categories"].iloc[0] == 1


# --- 19 · regularisation ---------------------------------------------------


def _correlated_design(n: int = 3000, seed: int = 0) -> tuple:
    """Two near-identical predictors plus noise columns. The lasso must break a tie."""
    rng = np.random.default_rng(seed)
    signal = rng.normal(size=n)
    twin = signal + rng.normal(scale=0.03, size=n)  # correlation ~0.999
    noise = rng.normal(size=(n, 5))
    X = np.column_stack([signal, twin, noise])
    y = rng.binomial(1, 1 / (1 + np.exp(-1.5 * signal)))
    columns = ["signal", "twin", *[f"noise{i}" for i in range(5)]]
    return X, y, columns


def test_lasso_keeps_one_of_a_correlated_pair_and_drops_the_other():
    """Not because one matters more. Because the penalty is indifferent and must choose."""
    X, y, columns = _correlated_design()
    split = len(y) // 2
    fit = fit_penalised(
        X[:split], y[:split], X[split:], y[split:], columns,
        name="lasso", penalty="l1", C=0.05,
    )
    kept = {c for c, k in zip(columns, fit.selected, strict=True) if k}
    # Exactly one of the two near-duplicates survives.
    assert len({"signal", "twin"} & kept) == 1


def test_ridge_and_lasso_score_the_same_while_selecting_differently():
    """The comparison the project turns on: prediction is stable, explanation is not."""
    X, y, columns = _correlated_design(seed=2)
    split = len(y) // 2
    ridge = fit_penalised(X[:split], y[:split], X[split:], y[split:], columns,
                          name="ridge", penalty="l2", C=0.05)
    lasso = fit_penalised(X[:split], y[:split], X[split:], y[split:], columns,
                          name="lasso", penalty="l1", C=0.05)

    assert abs(ridge.test_auc - lasso.test_auc) < 0.02
    assert lasso.n_selected < ridge.n_selected


def test_bootstrap_selection_separates_real_features_from_noise():
    X, y, columns = _correlated_design(seed=3)
    stability = bootstrap_selection(X, y, columns, C=0.05, replicates=30, seed=0)
    frequency = dict(zip(stability["column"], stability["selected_share"], strict=True))

    # One of the correlated pair is always kept; the pure-noise columns are chosen less often.
    # Stated as a gap rather than a threshold: at C=0.05 the penalty is weak enough that a
    # noise column survives most resamples, which is itself the point of measuring this.
    assert max(frequency["signal"], frequency["twin"]) > 0.8
    assert max(frequency["signal"], frequency["twin"]) > max(
        frequency[f"noise{i}"] for i in range(5)
    )


def test_jaccard_is_one_for_identical_sets_and_zero_for_disjoint_ones():
    a = np.array([True, True, False, False])
    b = np.array([False, False, True, True])
    assert jaccard(a, a) == 1.0
    assert jaccard(a, b) == 0.0
    assert jaccard(np.zeros(4, dtype=bool), np.zeros(4, dtype=bool)) == 1.0


def test_pairwise_stability_returns_overlaps_in_range():
    X, y, _ = _correlated_design(seed=4)
    overlaps = pairwise_stability(X, y, C=0.05, replicates=6, seed=0)
    assert len(overlaps) == 15  # 6 choose 2
    assert ((overlaps >= 0) & (overlaps <= 1)).all()


# --- 20 · market basket ----------------------------------------------------


def _basket_frame() -> pd.DataFrame:
    """Two real associations planted in a sea of popular items."""
    rng = np.random.default_rng(5)
    rows = []
    for invoice in range(1500):
        items = set(rng.choice(["p0", "p1", "p2", "p3", "p4"], size=3, replace=False))
        if invoice % 5 == 0:
            items |= {"pairA", "pairB"}  # a genuine association
        rows.extend({"Invoice": str(invoice), "Description": item} for item in items)
    return pd.DataFrame(rows)


def test_a_planted_association_shows_up_with_high_lift():
    baskets = build_baskets(_basket_frame(), basket_col="Invoice", item_col="Description")
    rules = build_rules(baskets, min_support_count=5, top_items=50)
    planted = rules[(rules["antecedent"] == "pairA") & (rules["consequent"] == "pairB")]

    assert len(planted) == 1
    assert planted["lift"].iloc[0] > 3.0
    assert planted["confidence"].iloc[0] > 0.9


def test_confidence_is_bounded_below_by_the_popularity_of_the_consequent():
    """The structural reason confidence rankings are popularity rankings."""
    baskets = build_baskets(_basket_frame(), basket_col="Invoice", item_col="Description")
    rules = build_rules(baskets, min_support_count=5, top_items=50)
    # Lift is exactly confidence / P(B), so this identity has to hold for every rule.
    assert np.allclose(rules["lift"], rules["confidence"] / rules["consequent_support"])


def test_the_permutation_null_destroys_the_planted_association():
    """If reshuffling did not remove it, the null would not be a null."""
    baskets = build_baskets(_basket_frame(), basket_col="Invoice", item_col="Description")
    real = build_rules(baskets, min_support_count=5, top_items=50)
    null = permutation_null(baskets, replicates=4, top_items=50, min_support_count=5, seed=0)

    assert real["lift"].max() > null["max_lift"].mean() * 1.5
    # Basket sizes and item popularity are preserved, so roughly as many rules survive.
    assert null["rules"].mean() > 0


def test_holdout_check_reports_rules_that_stop_holding():
    """A rule present in one period and absent from the next must be marked as not held."""
    frame = _basket_frame()
    baskets = build_baskets(frame, basket_col="Invoice", item_col="Description")
    rules = build_rules(baskets, min_support_count=5, top_items=50)

    # A later period where the planted pair never co-occurs.
    rng = np.random.default_rng(6)
    later = [
        frozenset(rng.choice(["p0", "p1", "p2", "p3", "p4", "pairA", "pairB"], 3, replace=False))
        for _ in range(800)
    ]
    check = holdout_check(rules.sort_values("lift", ascending=False), later, top=10)
    planted = check[(check["antecedent"] == "pairA") & (check["consequent"] == "pairB")]
    assert len(planted) == 1
    assert planted["lift_later"].iloc[0] < planted["lift_discovered"].iloc[0]


def test_baskets_are_sets_so_quantity_cannot_inflate_a_pair():
    frame = pd.DataFrame(
        {"Invoice": ["1"] * 5, "Description": ["a", "a", "a", "b", "b"]}
    )
    baskets = build_baskets(frame, basket_col="Invoice", item_col="Description")
    assert baskets == [frozenset({"a", "b"})]
    assert pair_counts(baskets)[("a", "b")] == 1
    assert item_counts(baskets)["a"] == 1


def test_enormous_baskets_are_excluded_from_pair_counts():
    """One 200-line wholesale order contributes 19,900 pairs and would dominate the counts."""
    huge = frozenset(f"item{i}" for i in range(200))
    normal = frozenset({"a", "b"})
    assert pair_counts([huge, normal], max_basket=60) == {("a", "b"): 1}
    assert len(pair_counts([huge, normal], max_basket=500)) == pytest.approx(19901, abs=1)
